In [1]:
from PIL import Image
import os
import numpy as np
data=np.genfromtxt('/home/zzq/research/windows_file/IIIT-CFW1.0/name',dtype=str,delimiter='\n')

In [5]:
root1='/home/zzq/research/windows_file/IIIT-CFW1.0/cartoonFaces_dest/'
root2='/home/zzq/research/windows_file/IIIT-CFW1.0/real_face_dest/'
train='/home/zzq/research/pix2pix-tensorflow/face/train/'
val='/home/zzq/research/pix2pix-tensorflow/face/val/'
size = 256,256
import Image
UNIT_SIZE = 256 # 单个图像的大小为229*229
TARGET_WIDTH = 2 * UNIT_SIZE # 拼接完后的横向长度为6*229
for i in range(len(data)):
    for j in range(10):
        file1=root1+data[i]+'/'+data[i]+str(j+1).zfill(4)+'.jpeg'
        if not os.path.isfile(file1):
            file1=root1+data[i]+'/'+data[i]+str(j+1).zfill(4)+'.jpg'
        im1=Image.open(file1)
        im11=im1.resize((256,256), Image.ANTIALIAS)
        file2=root2+data[i]+'/'+data[i]+str(j+1).zfill(4)+'.jpg'
        im2=Image.open(file2)
        im22=im2.resize((256,256), Image.ANTIALIAS)
        target = Image.new('RGB', (TARGET_WIDTH,UNIT_SIZE)) 
        target.paste(im11, (0, 0, 256, UNIT_SIZE))# 将image复制到target的指定位置中
        target.paste(im22, (256, 0, 512, UNIT_SIZE))# 将image复制到target的指定位置中
        if j<8:
            destfile=train+data[i]+str(j+1).zfill(4)+'.jpg'
        else:
            destfile=val+data[i]+str(j+1).zfill(4)+'.jpg'
        target.save(destfile)

In [1]:
import os
import numpy as np
data=np.genfromtxt('/home/zzq/research/windows_file/IIIT-CFW1.0/name',dtype=str,delimiter='\n')

In [5]:
root1='/home/zzq/research/windows_file/IIIT-CFW1.0/cartoonFaces_dest/'
dest='/home/zzq/research/windows_file/IIIT-CFW1.0/label_cartoon/'

size = 256,256
import Image
# UNIT_SIZE = 256 # 单个图像的大小为229*229
# TARGET_WIDTH = 2 * UNIT_SIZE # 拼接完后的横向长度为6*229
for i in range(len(data)):
    for j in range(300):
        file1=root1+data[i]+'/'+data[i]+str(j+1).zfill(4)+'.jpeg'
        if not os.path.isfile(file1):
            file1=root1+data[i]+'/'+data[i]+str(j+1).zfill(4)+'.jpg'
            if not os.path.isfile(file1):
                pass
            else:
                im1=Image.open(file1)
                im11=im1.resize((256,256), Image.ANTIALIAS)
                destfile=dest+data[i]+str(j+1).zfill(4)+'.jpg'
                im11.save(destfile)
        else:
            im1=Image.open(file1)
            im11=im1.resize((256,256), Image.ANTIALIAS)
            destfile=dest+data[i]+str(j+1).zfill(4)+'.jpg'
            im11.save(destfile)

In [6]:
root='/home/zzq/research/windows_file/IIIT-CFW1.0/label_cartoon/'
for i in range(len(data)):
    for j in range(10):
        destfile=root+data[i]+str(j+1).zfill(4)+'.jpg'
        os.remove(destfile)

In [1]:
import os
import numpy as np
data=np.genfromtxt('/home/zzq/research/windows_file/IIIT-CFW1.0/name',dtype=str,delimiter='\n')
dest='/home/zzq/PycharmProjects/cartoon_gan/img/'
for i in range(len(data)):
    dir_name=dest+data[i]
    if not os.path.exists(dir_name):
        os.mkdir(dir_name)

In [2]:
root1='/home/zzq/research/windows_file/IIIT-CFW1.0/cartoonFaces_dest/'
dest='/home/zzq/PycharmProjects/cartoon_gan/img/'

size = 256,256
import Image
# UNIT_SIZE = 256 # 单个图像的大小为229*229
# TARGET_WIDTH = 2 * UNIT_SIZE # 拼接完后的横向长度为6*229
for i in range(len(data)):
    for j in range(300):
        file1=root1+data[i]+'/'+data[i]+str(j+1).zfill(4)+'.jpeg'
        if not os.path.isfile(file1):
            file1=root1+data[i]+'/'+data[i]+str(j+1).zfill(4)+'.jpg'
            if not os.path.isfile(file1):
                pass
            else:
                im1=Image.open(file1)
                im11=im1.resize((256,256), Image.ANTIALIAS)
                destfile=dest+data[i]+'/'+data[i]+str(j+1).zfill(4)+'.jpg'
                im11.save(destfile)
        else:
            im1=Image.open(file1)
            im11=im1.resize((256,256), Image.ANTIALIAS)
            destfile=dest+data[i]+'/'+data[i]+str(j+1).zfill(4)+'.jpg'
            im11.save(destfile)

In [3]:
dest='/home/zzq/PycharmProjects/cartoon_gan/img/'
for i in range(len(data)):
    for j in range(10):
        destfile=dest+data[i]+'/'+data[i]+str(j+1).zfill(4)+'.jpg'
        os.remove(destfile)

In [4]:
classes={'husky','chihuahua'}
print type(classes)

<type 'set'>


In [5]:
print type(data)

<type 'numpy.ndarray'>


In [6]:
cls=set(data)

In [7]:
print type(cls)

<type 'set'>


In [8]:
for index,name in enumerate(cls):
    print index

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [1]:
import numpy as np
print np.eye(4)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [7]:
import os
import glob
from PIL import Image
name_list=[]
for files in glob.glob('/home/zzq/research/windows_file/KDEF/AF01/*.JPG'):
    filepath, filename = os.path.split(files)
    # print filename
    fin=filename.split(".")
    name=fin[0]
    # print name
    str_=name[4:]
    print str_
    name_list.append(str_)

DIFL
HAHR
NEHL
SUFL
ANS
SAS
SAFR
HAFL
SUFR
AFFL
NES
SUHR
AFHR
DIS
SUHL
HAFR
DIFR
AFHL
AFS
HAS
AFFR
SAHL
HAHL
SAHR
ANFR
ANHR
ANFL
NEFR
SUS
DIHL
SAFL
DIHR
NEHR
ANHL
NEFL


In [8]:
out=file("/home/zzq/research/windows_file/KDEF_cls_label","w")
for i in range(len(name_list)):
    out.write(name_list[i]+'\n')
out.close()

In [17]:
root='/home/zzq/research/windows_file/KDEF'
dest='/home/zzq/research/windows_file/KDEF_resize'
size=256,256
for i in range(35):
    dir_name='AF'+str(i+1).zfill(2)
    os.mkdir(dest+'/'+dir_name)
    name_jpg=root+'/'+dir_name+'/*.JPG'
    for files in glob.glob(name_jpg):
        img=Image.open(files)
        filepath, filename = os.path.split(files)
        img=img.resize((256,256),Image.ANTIALIAS)
        filename=filename[4:]
        img.save(dest+'/'+dir_name+'/'+filename)

In [18]:
def resize_my(name):
    root='/home/zzq/research/windows_file/KDEF'
    dest='/home/zzq/research/windows_file/KDEF_resize'
    # size=256,256
    for i in range(35):
        dir_name=name+str(i+1).zfill(2)
        os.mkdir(dest+'/'+dir_name)
        name_jpg=root+'/'+dir_name+'/*.JPG'
        for files in glob.glob(name_jpg):
            img=Image.open(files)
            filepath, filename = os.path.split(files)
            img=img.resize((256,256),Image.ANTIALIAS)
            filename=filename[4:]
            img.save(dest+'/'+dir_name+'/'+filename)

In [19]:
resize_my('AM')
resize_my('BF')
resize_my('BM')

In [13]:
print name_list

['DIFL', 'HAHR', 'NEHL', 'SUFL', 'ANS', 'SAS', 'SAFR', 'HAFL', 'SUFR', 'AFFL', 'NES', 'SUHR', 'AFHR', 'DIS', 'SUHL', 'HAFR', 'DIFR', 'AFHL', 'AFS', 'HAS', 'AFFR', 'SAHL', 'HAHL', 'SAHR', 'ANFR', 'ANHR', 'ANFL', 'NEFR', 'SUS', 'DIHL', 'SAFL', 'DIHR', 'NEHR', 'ANHL', 'NEFL']


In [14]:
print name_list

['DIFL', 'HAHR', 'NEHL', 'SUFL', 'ANS', 'SAS', 'SAFR', 'HAFL', 'SUFR', 'AFFL', 'NES', 'SUHR', 'AFHR', 'DIS', 'SUHL', 'HAFR', 'DIFR', 'AFHL', 'AFS', 'HAS', 'AFFR', 'SAHL', 'HAHL', 'SAHR', 'ANFR', 'ANHR', 'ANFL', 'NEFR', 'SUS', 'DIHL', 'SAFL', 'DIHR', 'NEHR', 'ANHL', 'NEFL']


In [15]:
import random
rand_int=random.randint(1,35)
rand_list=random.sample(range(1,36),7)
print rand_list

[13, 11, 19, 9, 7, 35, 8]


In [16]:
print range(1,36)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]


In [31]:
def merge(cls_name):
    root='/home/zzq/research/windows_file/KDEF_resize/'
    dest='/home/zzq/research/windows_file/KDEF_merge/'
    for i in range(17):
        root1=root+cls_name+str(2*i+1).zfill(2)+'/'
        root2=root+cls_name+str(2*i+2).zfill(2)+'/'
        # for j in range(len(name_list)):
        x=set(range(1,36))
        y=set(random.sample(range(1,36),7))
        train_list=list(x-y)
        val_list=list(y)
        # print val_list
        train_dest=dest+'train/'
        for j in range(len(train_list)):
            img1=Image.open(root1+name_list[train_list[j]-1]+'.JPG')
            img2=Image.open(root2+name_list[train_list[j]-1]+'.JPG')
            target = Image.new('RGB', (512,256)) 
            target.paste(img1, (0, 0, 256, 256))# 将image复制到target的指定位置中
            target.paste(img2, (256, 0, 512, 256))# 将image复制到target的指定位置中
            target.save(train_dest+cls_name+str(2*i+1).zfill(2)+str(2*i+2).zfill(2)+name_list[train_list[j]-1]+'.jpg')
        val_dest=dest+'val/'
        for j in range(len(val_list)):
            img1=Image.open(root1+name_list[val_list[j]-1]+'.JPG')
            img2=Image.open(root2+name_list[val_list[j]-1]+'.JPG')
            target = Image.new('RGB', (512,256)) 
            target.paste(img1, (0, 0, 256, 256))# 将image复制到target的指定位置中
            target.paste(img2, (256, 0, 512, 256))# 将image复制到target的指定位置中
            target.save(val_dest+cls_name+str(2*i+1).zfill(2)+str(2*i+2).zfill(2)+name_list[val_list[j]-1]+'.jpg')

In [34]:
merge('AF')
merge('AM')
merge('BF')
merge('BM')